### ISSUE TITLE
Custom message package osn't adding std_msg reference into csproj

### ISSUE THREAD

**Issue by tank104** [RobotecAI/ros2cs#31] opened 2022-09-15 21:48 UTC
Hi,
I am having real troubles getting std_msgs_assembly.dll referenced in the csproj that is built for my custom_message package.

My setup is this:
CMakeLists.txt:
`...
find_package(ament_cmake REQUIRED)
find_package(std_msgs REQUIRED)
find_package(rosidl_default_generators REQUIRED)
...
  rosidl_generate_interfaces(${PROJECT_NAME}
                             ${ANDREW_TEST_MSGS}
                             DEPENDENCIES
                             std_msgs
                             ADD_LINTER_TESTS)
...`

package.xml is this:
`...
  <depend>ros_environment</depend>
  <depend>std_msgs</depend>
...`

But in the output after running colcon in test_assembly_dotnetcore.csproj I get this:
`...
 <ItemGroup>
    <Reference Include="/home/andrew/ros2cs/install/lib/dotnet/ros2cs_common.dll" />
  </ItemGroup>
...`

I would expect to see std_msgs dll reference there.  As right now I get build errors when the csproj is built because std_msg could not be found.

Hopefully I am really not understanding how to set up new custom_messages, and its a quick fix, but I have spent hours trying to understand and get it working.

**Comment by Deric-W** [comment] 2022-09-29 11:47
I have the same problem (with geometry_msgs) while building a part of the package created [here](https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Custom-ROS2-Interfaces.html).
My ROS2 version is humble and the output is riddled with the following warning:

```
SC : warning CS1668: Invalid search path 'lib\um\x64' specified in 'LIB environment variable' -- 'directory does not exist' [C:\dev\ros2-for-unity\build\ros2_custom_msgs\ros2_custom_msgs_assembly\ros2_custom_msgs_assembly_dotnetcore.csproj] [C:\dev\ros2-for-unity\build\ros2_custom_msgs\ros2_custom_msgs_assembly.vcxproj]
```

followed by:

```
C:\dev\ros2-for-unity\build\ros2_custom_msgs\rosidl_generator_cs\ros2_custom_msgs\msg\sphere.cs(31,10): error CS0246: The type or namespace name 'geometry_msgs' could not be found (are you missing a using directive or an assembly reference?) [C:\dev\ros2-for-unity\build\ros2_custom_msgs\ros2_custom_msgs_assembly\ros2_custom_msgs_assembly_dotnetcore.csproj] [C:\dev\ros2-for-unity\build\ros2_custom_msgs\ros2_custom_msgs_assembly.vcxproj]
```

I tried copying parts of the CMakeLists.txt of geometry_msgs, but it did not help.

**Comment by Deric-W** [comment] 2022-09-29 13:26
I managed to make the build succeed, it seems to be related to [ros2-for-unity](https://github.com/RobotecAI/ros2-for-unity).
I created an [Issue ](https://github.com/RobotecAI/ros2-for-unity/issues/49)there.

**Comment by pijaro** [comment] 2022-11-07 10:57
I've also tried to reproduce it on my machine but without success. I tested the tutorial packages as described [here](https://github.com/RobotecAI/ros2-for-unity/issues/49#issuecomment-1300441662), and I'm ending up with a correctly filled `csproj` file.

`build/tutorial_interfaces/tutorial_interfaces_assembly/tutorial_interfaces_assembly_dotnetcore.csproj`:
```xml
...
  <ItemGroup>
    <Reference Include="/home/pj/ros2cs/install/lib/dotnet/ros2cs_common.dll" /> <Reference Include="/home/pj/ros2cs/install/lib/dotnet/geometry_msgs_assembly.dll" /> <Reference Include="/home/pj/ros2cs/install/lib/dotnet/std_msgs_assembly.dll" /> <Reference Include="/home/pj/ros2cs/install/lib/dotnet/builtin_interfaces_assembly.dll" />
  </ItemGroup>
...
```

Therefore, could you post a full build log and tell me which versions of `ros2cs`, Ubuntu, and ROS2 you are using?

**Comment by pijaro** [comment] 2022-11-08 10:31
Ok, closing then.

**Closed by pijaro** 2022-11-08 10:31 UTC
